# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.6
  - 7.0

notifications:
  email:
    - gregory@tiv.net

before_script:
    - composer self-update
    - composer install --dev --no-interaction --prefer-source

script:
    - phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
